fix(owasp): - fixes owasp cache - put unit tests after owasp dependency check to use cached build from there and cache override specify owasp dependency check cache key - change secret with role arn
fix: add regex check for AWS_DEPLOYMENT_ROLE_ARN

diff --git a/.github/workflows/backend_build_push_image.yml b/.github/workflows/backend_build_push_image.yml
--- a/.github/workflows/backend_build_push_image.yml
+++ b/.github/workflows/backend_build_push_image.yml
@@ -30,6 +30,26 @@ on:
         value: ${{ jobs.build-push-image.outputs.image }}
 
 jobs:
+  # Validate secrets to match an expected regex pattern to facilitate debugging of misconfigured secrets.
+  validate-secret-values:
+    runs-on: ubuntu-latest
+    environment:  ${{ inputs.environment }}
+    steps:
+      - name: Validate secret values
+        env:
+          AWS_DEPLOYMENT_ROLE_ARN: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
+          AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
+        run: |
+          echo "Validating secret values for environment ${{ inputs.environment }}"
+          AWS_ROLE_PATTERN='^arn:aws:iam::[0-9]{12}:role\/[A-Za-z0-9+=,.@_-]+$'
+          echo "Roles should match pattern: $AWS_ROLE_PATTERN"
+          if [[ ! "$AWS_DEPLOYMENT_ROLE_ARN" =~ $AWS_ROLE_PATTERN ]]; then
+            echo "Invalid AWS_DEPLOYMENT_ROLE_ARN, does not match pattern $AWS_ROLE_PATTERN"
+            echo "Secret value length: ${#AWS_DEPLOYMENT_ROLE_ARN}"
+            exit 1
+          fi
+          echo "All secret values are valid"
+
   build-push-image:
     name: "Build and push docker image to ECR  ${{ inputs.environment }} - ${{ inputs.version }}"
     runs-on: ubuntu-latest
@@ -57,6 +77,7 @@ jobs:
           set -euo pipefail
           [[ "$VERSION" =~ ^[0-9]+(\.[0-9]+){2}([.-][0-9A-Za-z]+)*$ ]] || { echo "Invalid version"; exit 1; }
           echo "VERSION=$VERSION" >> "$GITHUB_ENV"
+          [[ "${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}" =~ ^arn:aws:iam::[0-9]{12}:role\/[A-Za-z0-9+=,.@_-]+$ ]] || { echo "Invalid AWS_DEPLOYMENT_ROLE_ARN, does not match pattern ^arn:aws:iam::\d+:role\/[\w-]+$"; exit 1; }
       - name: Checkout
         uses: actions/checkout@v6
         with:
@@ -85,17 +106,8 @@ jobs:
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v6
         with:
-          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
+          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
           aws-region: ${{ env.AWS_REGION }}
-
-      # activate once blueprint is ready
-      #      - name: Assume deployment role
-      #        uses: aws-actions/configure-aws-credentials@v4
-      #        with:
-      #          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
-      #          aws-region: ${{ env.AWS_REGION }}
-      #          role-chaining: true
-      #          role-skip-session-tagging: true
 
       - name: Login to AWS ECR
         id: login-ecr
